  CREATE TABLE USERS(
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(32) NOT NULL ,
      password VARCHAR(32) NOT NUll,
      email VARCHAR(64) NOT NULL,
      enabled BIT,
      locked BIT,
      USER_ROLE VARCHAR(10),
      USER_CODE VARCHAR(300)
  );

  CREATE TABLE LECTURES (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(32) NOT NULL ,
      description VARCHAR(500) NOT NULL,
      sits INT NOT NULL,
      LECTURES_CODE VARCHAR(300)

  );